# Test functions
import sys
sys.path.insert(0, "src")  # prepend src to sys.path

import os
import unittest
from PIL import Image
from finhash import FINDHasher

MEME_DIR = os.path.join(
    os.path.dirname(__file__), "..", "summative2026", "meme_images"
)
MEME_IMAGES_AVAILABLE = os.path.isdir(MEME_DIR)

# Reference hashes generated by the original unmodified FINd.py.
# These span 5 different meme families to test diverse image content.
REFERENCE_HASHES = [
    ("0000_12268686.jpg", "393b246d65a694dc5386279b8e7394f04c9da697877b18a31995ab9893235b65"),
    ("0040_10269762.jpg", "94eed06973de1979b46e8cb971252fdce552c5a12aa426538516ffc408c5f6a1"),
    ("0264_33825691.jpg", "7f6334931816edc650767ba4bc1ec87636f00bb4ee01416793ae2dc15c13973e"),
    ("0547_15350190.jpg", "38ff6458f3bd4199cbee8d0d26123c6535a2f072c85227126e4d3999b825be6d"),
    ("1016_32680295.jpg", "b00b02e4bceeff909b6d5bc86948e7674fe6e625f6b1df69440810de4f318105"),
]


class TestFINDHasher(unittest.TestCase):
    """Verify that the optimized FINDHasher produces bit-identical hashes
    to the original FINd algorithm by comparing against known references."""

    @classmethod
    def setUpClass(cls):
        """Create a shared hasher instance (DCT matrix computed once)."""
        cls.hasher = FINDHasher()

    def test_dct_matrix_dimensions(self):
        """DCT matrix is 16x64 as expected."""
        self.assertIsNotNone(self.hasher.DCT_matrix)
        self.assertEqual(len(self.hasher.DCT_matrix), 16)
        self.assertEqual(len(self.hasher.DCT_matrix[0]), 64)

    @unittest.skipUnless(MEME_IMAGES_AVAILABLE, "meme dataset not present")
    def test_hash_matches_original_family_0000(self):
        """Optimized hash matches original FINd.py for family 0000."""
        fname, expected = REFERENCE_HASHES[0]
        h = self.hasher.fromFile(os.path.join(MEME_DIR, fname))
        self.assertEqual(str(h), expected)

    @unittest.skipUnless(MEME_IMAGES_AVAILABLE, "meme dataset not present")
    def test_hash_matches_original_family_0040(self):
        """Optimized hash matches original FINd.py for family 0040."""
        fname, expected = REFERENCE_HASHES[1]
        h = self.hasher.fromFile(os.path.join(MEME_DIR, fname))
        self.assertEqual(str(h), expected)

    @unittest.skipUnless(MEME_IMAGES_AVAILABLE, "meme dataset not present")
    def test_hash_matches_original_family_0264(self):
        """Optimized hash matches original FINd.py for family 0264."""
        fname, expected = REFERENCE_HASHES[2]
        h = self.hasher.fromFile(os.path.join(MEME_DIR, fname))
        self.assertEqual(str(h), expected)

    @unittest.skipUnless(MEME_IMAGES_AVAILABLE, "meme dataset not present")
    def test_hash_matches_original_family_0547(self):
        """Optimized hash matches original FINd.py for family 0547."""
        fname, expected = REFERENCE_HASHES[3]
        h = self.hasher.fromFile(os.path.join(MEME_DIR, fname))
        self.assertEqual(str(h), expected)

    @unittest.skipUnless(MEME_IMAGES_AVAILABLE, "meme dataset not present")
    def test_hash_matches_original_family_1016(self):
        """Optimized hash matches original FINd.py for family 1016."""
        fname, expected = REFERENCE_HASHES[4]
        h = self.hasher.fromFile(os.path.join(MEME_DIR, fname))
        self.assertEqual(str(h), expected)

    @unittest.skipUnless(MEME_IMAGES_AVAILABLE, "meme dataset not present")
    def test_hash_is_256_bit(self):
        """Hash output is exactly 256 bits (16x16)."""
        fname = REFERENCE_HASHES[0][0]
        h = self.hasher.fromFile(os.path.join(MEME_DIR, fname))
        self.assertEqual(len(h.hash), 256)

    @unittest.skipUnless(MEME_IMAGES_AVAILABLE, "meme dataset not present")
    def test_same_image_zero_distance(self):
        """Hashing the same image twice produces Hamming distance 0."""
        path = os.path.join(MEME_DIR, REFERENCE_HASHES[0][0])
        h1 = self.hasher.fromFile(path)
        h2 = self.hasher.fromFile(path)
        self.assertEqual(h1 - h2, 0)

    @unittest.skipUnless(MEME_IMAGES_AVAILABLE, "meme dataset not present")
    def test_different_families_large_distance(self):
        """Images from different families have large Hamming distance."""
        h1 = self.hasher.fromFile(os.path.join(MEME_DIR, REFERENCE_HASHES[0][0]))
        h2 = self.hasher.fromFile(os.path.join(MEME_DIR, REFERENCE_HASHES[1][0]))
        self.assertGreater(h1 - h2, 40)

    @unittest.skipUnless(MEME_IMAGES_AVAILABLE, "meme dataset not present")
    def test_batch_correctness_against_original(self):
        """Cross-check a larger batch against the original FINd.py at runtime.

        Imports the original unmodified FINd.py and compares hashes on 20
        images to ensure the optimized version is faithful beyond the 5
        reference fixtures.
        """
        orig_dir = os.path.join(os.path.dirname(__file__), "..", "summative2026")
        sys.path.insert(0, orig_dir)
        try:
            from FINd import FINDHasher as OriginalHasher
        finally:
            sys.path.pop(0)

        original = OriginalHasher()
        all_images = sorted(os.listdir(MEME_DIR))[:20]

        for fname in all_images:
            with self.subTest(image=fname):
                path = os.path.join(MEME_DIR, fname)
                h_orig = original.fromFile(path)
                h_opt = self.hasher.fromFile(path)
                self.assertEqual(str(h_opt), str(h_orig))


    def test_nonsquare_image_does_not_crash(self):
        """Non-square images are handled correctly.

        The original FINd boxFilter uses k*rows+l as the flat-array index
        instead of k*cols+l. For non-square images where rows > cols, this
        causes an IndexError (out-of-bounds write). Our optimized version
        fixes this by using the correct row-major stride (cols).
        """
        # Create a synthetic non-square RGB image (wide landscape)
        wide_img = Image.new("RGB", (400, 200), color=(128, 64, 32))
        h = self.hasher.fromImage(wide_img)
        self.assertEqual(len(h.hash), 256)

        # Create a tall portrait image (rows > cols — would crash original)
        tall_img = Image.new("RGB", (200, 400), color=(32, 64, 128))
        h2 = self.hasher.fromImage(tall_img)
        self.assertEqual(len(h2.hash), 256)

        # The two should produce different hashes (different aspect ratios)
        self.assertNotEqual(str(h), str(h2))

    def test_nonsquare_deterministic(self):
        """Non-square image hashes are deterministic."""
        img = Image.new("RGB", (300, 150), color=(100, 100, 100))
        h1 = self.hasher.fromImage(img)
        h2 = self.hasher.fromImage(img)
        self.assertEqual(h1 - h2, 0)


if __name__ == "__main__":
    unittest.main()
